### ISSUE TITLE
reset state does not reset Map() filed in defaults

### ISSUE THREAD

**Issue by ubaidazad** [ng-turkey/ngxs-reset-plugin#85] opened 2023-08-09 15:59 UTC
**`StateResetAll` reset state to default values but Map objects are not reset**
Whenever you dispatch `StateResetAll` it perfectly resets the state but what happens if default state field is Map it is not getting reset to new Map() and old value is returned to listeners leading to unintentional results.

```
@State<ApplicationSettingsStateModel>({
  name: 'applicationSettings',
  defaults: {
    settings: new Map(),
    settingsDict: {},
  },
})
@Injectable()
export class ApplicationSettingsState {
}
```

here settings in defaults is not reset to `new Map()` but settingsDict is set to `{}`

**Comment by armanozak** [comment] 2023-08-17 12:13
[NGXS recommends avoiding class instances in your state](https://www.ngxs.io/recipes/style-guide#avoid-saving-class-based-instances-in-your-state) because your state should be immutable and serializable/deserializable. Nevertheless, if you don't worry about serialization and still want to use a `Map`, you must make sure your state changes are immutable. In other words, you should create a new `Map` instance any time you want to update your state. I forked our pizza example to show you how it works.

https://stackblitz.com/edit/ngxs-pizza-with-map?file=src%2Fapp%2Fpizza%2Fpizza.state.ts,src%2Fapp%2Forder%2Forder.handler.ts

If you check line 55 in the pizza.state.ts file, you'll see a new `Map` instance is created with the current state and the state is updated with it. The order.handler.ts file proves this works with `StateResetAll`.

Please let us know if your question is answered.

**Comment by gokhanipek** [comment] 2024-01-18 13:01
Condisering the issue is open for 5 months and no follow up, maybe we can close the issue?

**Comment by armanozak** [comment] 2024-01-18 13:02
I guess we can. Thanks for reminding @gokhanipek. 👍

**Closed by armanozak** 2024-01-18 13:02 UTC
